services:
  - name: webview-app
    type: web
    env: static
    staticPublishPath: . # O diretório atual será usado para publicar arquivos estáticos
    buildCommand: "" # Sem necessidade de build para arquivos estáticos simples
    startCommand: "" # Sem necessidade de start command para serviços estáticos
    regions:
      - oregon # Alterar para uma região disponível no Render, se necessário
    customDomains:
      - your-custom-domain.com # Substitua pelo seu domínio ou remova esta linha se não for usar
